### ISSUE TITLE
Whats the reason to put the email in the image alt property?

### ISSUE THREAD

**Issue by ialex** [KyleAMathews/react-gravatar#4]
What's the reason to have the email inside the alt property in the image element isn't it exposing unnecessary data?

```
alt={@props.email}
```

**Comment by KyleAMathews** [comment]
You're right. Most often people wouldn't want that there. I'll remove it.

**Comment by KyleAMathews** [comment]
Released a 2.0 as this is technically a breaking change.

**Comment by ialex** [comment]
Cool thanks for super fast support.
