### ISSUE TITLE
Not compatible with React v15

### ISSUE THREAD

**Issue by Danita** [KyleAMathews/react-gravatar#42]
It throws "Uncaught TypeError: React.__spread is not a function".

**Comment by KyleAMathews** [comment]
There's a fix for this in the soon to be released 15.0.1 https://github.com/facebook/react/pull/6454

This will also warn until https://github.com/jsdf/coffee-react-transform/issues/70 is fixed.

**Comment by Danita** [comment]
I see, it's a problem in the transpilation of the object spread operator. Thanks!

**Comment by KyleAMathews** [comment]
15.0.1 is released so things should work again!
