### ISSUE TITLE
Update react-dom to version 15.0.1

### ISSUE THREAD

**Issue by yuliroth** [KyleAMathews/react-gravatar#45]
Hello Kyle, are you planing to merge this PR soon https://github.com/KyleAMathews/react-gravatar/pull/44? 
its creating me a problem to upgrade my local rect to 15 v. 

Thank you

**Comment by agentcooper** [comment]
Update to `coffee-react` 5.0.0 (https://github.com/jsdf/coffee-react/commit/c46b0ab3b6a8d56636236de51da3b2ed4cc41efa) would also be nice, since it fixes `__spread` issue.

**Comment by KyleAMathews** [comment]
Both upgrades done and a 2.4.1 released! Let me know if there's any more trouble.
