### ISSUE TITLE
Example page is missing a JS file

### ISSUE THREAD

**Issue by TimFletcher** [KyleAMathews/react-gravatar#5]
When I visit http://kyleamathews.github.io/react-gravatar/examples/ I'm seeing a blank page and getting the following in Chrome's console.

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://kyleamathews.github.io/react-gravatar/examples/bundle.js

**Comment by KyleAMathews** [comment]
Oops! The link to the demo was wrong. Fixed in https://github.com/KyleAMathews/react-gravatar/commit/d6ce3794d898d41180b8d7f726fc3d6a949c8443

**Comment by TimFletcher** [comment]
Haha. No worries. Thanks for this project!
