### ISSUE TITLE
Support for IE?

### ISSUE THREAD

**Issue by epilande** [KyleAMathews/react-gravatar#54]
Hi, it would be awesome if this package could support IE.

The problem is `Object.assign` is not supported in IE 😕 
And the dist file `node_modules/react-gravatar/dist/index.js` uses `Object.assign`.

![screen shot 2016-05-15 at 1 44 22 am](https://cloud.githubusercontent.com/assets/3210082/15273821/b66be48a-1a3f-11e6-812a-2bfdb4620de8.png)

Running it through `babel-plugin-transform-object-assign` should work.

**Comment by KyleAMathews** [comment]
I converted the src to use Babel instead of Coffeescript so with the new 2.4.4 release, this shouldn't be an issue anymore 🎉
