### ISSUE TITLE
Build failing after upgrading

### ISSUE THREAD

**Issue by satazor** [KyleAMathews/react-gravatar#61]
After updating to the newest version, my webpack build is failing. Any ideas?

```
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/satazor/Work/npms/npms-www/node_modules/react-gravatar/.babelrc" at 0, attempted to resolve relative to "/Users/satazor/Work/npms/npms-www/node_modules/react-gravatar"
```

**Comment by KyleAMathews** [comment]
You need to exclude node_modules from babel_loader.

**Comment by satazor** [comment]
I've fixed it, thanks for the tip.

**Comment by mtetno** [comment]
Please write  how did u fixed this?

**Comment by KyleAMathews** [comment]
@mtetno if you're seeing the same error, make sure your webpack is setup the same as here: https://github.com/babel/babel-loader#usage

**Comment by KyleAMathews** [comment]
Specifically the `exclude` key.
