### ISSUE TITLE
Implement Recommended Gravatar Format?

### ISSUE THREAD

**Issue by AlexanderNull** [KyleAMathews/react-gravatar#86]
The recommended input format for an email should be in lowercase and trimmed of any white space in order to get the correct MD5 hash match. It doesn't look like this component implements such formatting on its own. Can we add this formatting into the component automatically or alternatively update the readme so that users know what format their input should be in?

**Comment by KyleAMathews** [comment]
This could be added to the component. Would you like to create a PR?

**Comment by AlexanderNull** [comment]
Certainly, I should be able to tackle it this weekend. Is there a significant use case for allowing case sensitive email input? If so we can maintain both functionality side by side with an additional prop.

**Comment by KyleAMathews** [comment]
I can't think of one. Emails aren't case sensitive (right?).

**Comment by AlexanderNull** [comment]
Hmm, apparently in the SMTP spec they can be (http://www.ietf.org/rfc/rfc2821.txt) for the local address portion, although it's discouraged in the spec from making use of case sensitivity. Hadn't anticipated that.

**Comment by KyleAMathews** [comment]
A better question perhaps is if the Gravatar system always lowercases
emails when someone sets up a picture. If that's the case then we'd have no
reason not to do the same.

**Comment by AlexanderNull** [comment]
I'll take a look.

**Comment by AlexanderNull** [comment]
Looks like you can't register two emails with the same characters, different case. From what I can find online, they changed to this case insensitive format a few years ago. Added a PR to both trim and lowercase the email before making hash as recommended by Gravatar.
https://github.com/KyleAMathews/react-gravatar/pull/93

**Comment by KyleAMathews** [comment]
Fixed in #93

**Comment by satazor** [comment]
@KyleAMathews can you release a new version? Thanks.

**Comment by KyleAMathews** [comment]
@satazor 2.5.1 is out

**Comment by satazor** [comment]
Ty @KyleAMathews. Also take a look at #130 when you got some time.
